### ISSUE TITLE
你好，跟踪你很久了！有个问题请教一下

### ISSUE THREAD

**Issue by zhangwenhaojf40** [alidili/Demos#1]
一个仓库下，创建多个Demo，这个怎么做啊 ？就像你这个Demos下放多个

**Comment by alidili** [comment]
先在github上建一个仓库，然后clone到本地，在Android Studio新建项目的时候把路径选在这个文件夹就可以了。@zhangwenhaojf40

**Comment by zhangwenhaojf40** [comment]
恩  ， 弄好了！太感谢了
