### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by zhangwenhao2013** [alidili/Demos#4]
看了你的文章, 了解了怎么使用Android profiler 查找内存泄漏, 但是只说到了查找到界面, 我想具体了解到instance view 的使用 ,具体了解是哪个持有了activity

**Comment by alidili** [comment]
点击发生泄漏的实例，可以在下面看到引用详情，Shallow Size代表该对象本身占用内存的大小，Retained Size代表该对象被释放后，垃圾回收器能回收的内存总和，不过这样看好像不太容易定位具体的泄漏位置，如果你以后有更好的方法可以分享下，借助第三方工具可以定位到具体的泄漏位置https://github.com/square/leakcanary
