### ISSUE TITLE
在有下面虚拟键的机型上上下移动略有不妥

### ISSUE THREAD

**Issue by anyanyan07** [alidili/Demos#5]
我是用的华为荣耀机型，屏幕下方有虚拟键。用你的demo测试时上下移动失效，排查原因得知，是因为虚拟键占用了屏幕，导致上移的时候是从虚拟键的位置开始的，所以移动不了。补充一点：UiObject back = uiDevice.findObject(new UiSelector().description("Navigate up"));这个在国产手机上也不可以，我替换成：UiObject back = uiDevice.findObject(new UiSelector().description("转到上一层级"));就ok了。

**Comment by alidili** [comment]
感谢反馈，国产Android ROM大部分都重写了UI部分，所以description可能和标准版不一样，这个使用uiautomatorviewer分析下就可以了。
