### ISSUE TITLE
部分手机滑动，在底部会显示虚线

### ISSUE THREAD

**Issue by githubtangchao** [alidili/Demos#7]
![lADPDgQ9qpxOATHNBnjNBNo_1242_1656](https://user-images.githubusercontent.com/48346363/56951434-6f541e80-6b6a-11e9-8c96-5106ff491d61.jpg)
![DINGTALK_IM_4142365513](https://user-images.githubusercontent.com/48346363/56951439-711de200-6b6a-11e9-8e70-265c8307d51b.JPG)
手机品牌： 魅族PRO6  系统 6.0

**Comment by alidili** [comment]
可以试下，在这个型号的手机上，使用标准的SeekBar，在底部会不会显示虚线

**Comment by githubtangchao** [comment]
但是在你demo看是没有的，我自己写的就有

**Comment by alidili** [comment]
直接运行Demo是没有虚线的吗，对比一下你的项目和Demo的主题有什么不同，然后测试下使用标准的SeekBar正常吗
