### ISSUE TITLE
您好,大佬想咨询一下 activity 怎么和 UiAutomator结合

### ISSUE THREAD

**Issue by shuyabin** [alidili/Demos#8]
大佬想咨询一下,我想通过activity的view 写入配置. 然后在通过写入的配置去执行不同的自动化测试.请问这个怎么做到?

**Comment by alidili** [comment]
不能在项目代码中调用测试用例，可以考虑用ADB的方式，在AS上执行测试用例，都是通过ADB命令来完成的
